<?php


namespace MP\Exchange\Export\CsvResolver;
use MP\Object\ObjectMetadata;

/**
 * Konfigurace pro import/export formatu CSV
 */
class CsvResolver
{
    protected static $relations = [
        ObjectMetadata::ELEVATOR => [160, 210, 260],
        ObjectMetadata::PLATFORM => [310, 350, 390, 430],
        ObjectMetadata::RAMP_SKIDS => [470, 510, 550, 590, 630, 670],
        ObjectMetadata::WC => [710, 780, 850, 920, 990],
    ];

    protected static $colsMap = [
        'main' => [
            1 => 'objectId',
            2 => 'parentObjectId',
            3 => 'userId',
            4 => 'certified',
            5 => 'photoUrl',
            6 => 'externalData',
            7 => 'title',
            8 => 'description',
            9 => 'license',
            10 => 'accessibility',
            11 => 'organizationIc',
            12 => 'organizationName',
            13 => 'mappingDate',
            14 => 'modifiedDate',
            15 => 'objectType',
            16 => 'objectTypeCustom',
            17 => 'latitude',
            18 => 'longitude',
            19 => 'ruianAddress',
            20 => 'zipcode',
            21 => 'region',
            22 => 'city',
            23 => 'cityPart',
            24 => 'street',
            25 => 'streetDescNo',
            26 => 'streetOrientNo',
            27 => 'streetOrientSymbol',
            28 => 'webUrl',
            29 => 'entrance1IsReservedParking',
            30 => 'entrance1NumberOfReservedParking',
            31 => 'entrance1ReservedParkingLocalization',
            32 => 'entrance1ReservedParkingAccessDescription',
            33 => 'entrance1IsLongitudinalInclination',
            34 => 'entrance1LongitudinalInclination',
            35 => 'entrance1LongitudinalInclinationLocalization',
            36 => 'entrance1IsTransverseInclination',
            37 => 'entrance1TransverseInclination',
            38 => 'entrance1TransverseInclinationLocalization',
            39 => 'entrance1IsDifficultSurface',
            40 => 'entrance1DifficultSurfaceDescription',
            41 => 'entrance1Guidingline',
            42 => 'entrance1Accessibility',
            43 => 'entrance1AreaBeforeDoorWidth',
            44 => 'entrance1AreaBeforeDoorDepth',
            45 => 'entrance1LobbyWidth',
            46 => 'entrance1LobbyDepth',
            47 => 'entrance1IsAOB',
            48 => 'entrance1AobIsAboveDoor',
            49 => 'entrance1AobLocalization',
            50 => 'entrance1HasDescription',
            51 => 'entrance1HasNotes',
            52 => 'entrance1BellType',
            53 => 'entrance1BellHeight',
            54 => 'entrance1BellIndentation',
            55 => 'entrance1Steps1NumberOf',
            56 => 'entrance1Steps1Height',
            57 => 'entrance1Steps1Depth',
            58 => 'entrance1Steps2NumberOf',
            59 => 'entrance1Steps2Height',
            60 => 'entrance1Steps2Depth',
            61 => 'entrance1ContrastMarkingIsGlassSurfaces',
            62 => 'entrance1ContrastMarkingLocalization',
            63 => 'entrance1StepsIsContrastMarked',
            64 => 'entrance1Door1MainpanelWidth',
            65 => 'entrance1Door1SidepanelWidth',
            66 => 'entrance1Door1Type',
            67 => 'entrance1Door1Opening',
            68 => 'entrance1Door1OpeningDirection',
            69 => 'entrance1Door1StepHeight',
            70 => 'entrance1Door2MainpanelWidth',
            71 => 'entrance1Door2SidepanelWidth',
            72 => 'entrance1Door2Type',
            73 => 'entrance1Door2Opening',
            74 => 'entrance1Door2OpeningDirection',
            75 => 'entrance1Door2StepHeight',
            76 => 'entrance2IsSideEntranceMarked',
            77 => 'entrance2IsSideEntranceInformation',
            78 => 'entrance2Localization',
            79 => 'entrance2Access',
            80 => 'entrance2AccessProvidedBy',
            81 => 'entrance2IsReservedParking',
            82 => 'entrance2NumberOfReservedParking',
            83 => 'entrance2ReservedParkingLocalization',
            84 => 'entrance2ReservedParkingAccessDescription',
            85 => 'entrance2IsLongitudinalInclination',
            86 => 'entrance2LongitudinalInclination',
            87 => 'entrance2LongitudinalInclinationLocalization',
            88 => 'entrance2IsTransverseInclination',
            89 => 'entrance2TransverseInclination',
            90 => 'entrance2TransverseInclinationLocalization',
            91 => 'entrance2IsDifficultSurface',
            92 => 'entrance2DifficultSurfaceDescription',
            93 => 'entrance2Guidingline',
            94 => 'entrance2Accessibility',
            95 => 'entrance2AreaBeforeDoorWidth',
            96 => 'entrance2AreaBeforeDoorDepth',
            97 => 'entrance2LobbyWidth',
            98 => 'entrance2LobbyDepth',
            99 => 'entrance2IsAOB',
            100 => 'entrance2AobIsAboveDoor',
            101 => 'entrance2AobLocalization',
            102 => 'entrance2HasDescription',
            103 => 'entrance2HasNotes',
            104 => 'entrance2BellType',
            105 => 'entrance2BellHeight',
            106 => 'entrance2BellIndentation',
            107 => 'entrance2Steps1NumberOf',
            108 => 'entrance2Steps1Height',
            109 => 'entrance2Steps1Depth',
            110 => 'entrance2Steps2NumberOf',
            111 => 'entrance2Steps2Height',
            112 => 'entrance2Steps2Depth',
            113 => 'entrance2ContrastMarkingIsGlassSurfaces',
            114 => 'entrance2ContrastMarkingLocalization',
            115 => 'entrance2StepsIsContrastMarked',
            116 => 'entrance2Door1MainpanelWidth',
            117 => 'entrance2Door1SidepanelWidth',
            118 => 'entrance2Door1Type',
            119 => 'entrance2Door1Opening',
            120 => 'entrance2Door1OpeningDirection',
            121 => 'entrance2Door1StepHeight',
            122 => 'entrance2Door2MainpanelWidth',
            123 => 'entrance2Door2SidepanelWidth',
            124 => 'entrance2Door2Type',
            125 => 'entrance2Door2Opening',
            126 => 'entrance2Door2OpeningDirection',
            127 => 'entrance2Door2StepHeight',
            128 => 'objectIsSteps',
            129 => 'objectSteps1NumberOf',
            130 => 'objectSteps1Height',
            131 => 'objectSteps1Depth',
            132 => 'objectSteps1Localization',
            133 => 'objectIsStairs',
            134 => 'objectStairsType',
            135 => 'objectStairsWidth',
            136 => 'objectStairsIsBannister',
            137 => 'objectIsNarrowedPassage',
            138 => 'objectNarrowedPassageWidth',
            139 => 'objectNarrowedPassageLocalization',
            140 => 'objectIsTourniquet',
            141 => 'objectTourniquetLocalization',
            142 => 'objectIsNavigationSystem',
            143 => 'objectNavigationSystemDescription',
            144 => 'objectInteriorAccessibility',
            145 => 'objectHasDescription',
            146 => 'objectHasNotes',
            147 => 'objectContrastMarkingIsGlassSurfaces',
            148 => 'objectContrastMarkingLocalization',
            149 => 'objectStepsIsContrastMarked',
            150 => 'objectIsAOB',
            151 => 'objectAobIsAboveDoor',
            152 => 'objectAobLocalization',
        ],
        ObjectMetadata::ELEVATOR => [
            1 => 'elevatorLocalization',
            2 => 'elevatorAccess',
            3 => 'elevatorType',
            4 => 'elevatorAccessProvidedBy',
            5 => 'elevatorConnectsFloors',
            6 => 'elevatorDriveoff',
            7 => 'elevatorControl1MaxHeight',
            8 => 'elevatorControl1ReliefMarking',
            9 => 'elevatorControl1FlatMarking',
            10 => 'elevatorIsControl1BrailleMarking',
            11 => 'elevatorIsAOB',
            12 => 'elevatorAobIsAboveDoor',
            13 => 'elevatorAobLocalization',
            14 => 'elevatorAOBAnnouncementsScheme',
            15 => 'elevatorIsCagePassthrough',
            16 => 'elevatorCageWidth',
            17 => 'elevatorCageDepth',
            18 => 'elevatorCageSeconddoorLocalization',
            19 => 'elevatorCageControlDistance',
            20 => 'elevatorCageControlHeight',
            21 => 'elevatorControl2ReliefMarking',
            22 => 'elevatorControl2FlatMarking',
            23 => 'elevatorIsControl2BrailleMarking',
            24 => 'elevatorIsCageControlAnnouncementAcoustic',
            25 => 'elevatorIsCageControlAnnouncementPhonetic',
            26 => 'elevatorIsCageHandle',
            27 => 'elevatorHandleLocalization',
            28 => 'elevatorIsCageMirror',
            29 => 'elevatorCageMirrorLocalization',
            30 => 'elevatorCageMirrorHeight',
            31 => 'elevatorIsCageSeat',
            32 => 'elevatorIsCageSeatWithinreach',
            33 => 'elevatorIsCageSeatFunctional',
            34 => 'elevatorHasNotes',
            35 => 'elevatorHasDescription',
            36 => 'entryareaWidth',
            37 => 'entryareaDepth',
            38 => 'entryareaHeightElevation',
            39 => 'door1Width',
            40 => 'door1Opening',
            41 => 'door2Width',
            42 => 'door2Opening',
        ],
        ObjectMetadata::PLATFORM => [
            1 => 'platformRelation',
            2 => 'platformLocalization',
            3 => 'platformAccess',
            4 => 'platformType',
            5 => 'platformMaxLoad',
            6 => 'platformWidth',
            7 => 'platformDepth',
            8 => 'platformIsMinParameters',
            9 => 'platformNumberOfSteps',
            10 => 'platformNumberOfFloors',
            11 => 'platformOutsideBottomControlHeight',
            12 => 'platformOutsideTopControlHeight',
            13 => 'platformInsideControlHeight',
            14 => 'platformHasNotes',
            15 => 'platformHasDescription',
            16 => 'entryarea1Entry',
            17 => 'entryarea1IsEntryClosing',
            18 => 'entryarea1EntryWidth',
            19 => 'entryarea1Width',
            20 => 'entryarea1Depth',
            21 => 'entryarea1HeightElevation',
            22 => 'entryarea1BellType',
            23 => 'entryarea1BellHeight',
            24 => 'entryarea1BellIndentation',
            25 => 'entryarea2Entry',
            26 => 'entryarea2IsEntryClosing',
            27 => 'entryarea2EntryWidth',
            28 => 'entryarea2Width',
            29 => 'entryarea2Depth',
            30 => 'entryarea2HeightElevation',
            31 => 'entryarea2BellType',
            32 => 'entryarea2BellHeight',
            33 => 'entryarea2BellIndentation',
        ],
        ObjectMetadata::RAMP_SKIDS => [
            1 => 'rampRelation',
            2 => 'rampLocalization',
            3 => 'rampInteriorLocalization',
            4 => 'rampMobility',
            5 => 'rampAccessProvidedBy',
            6 => 'rampType',
            7 => 'rampNumberOfLegs',
            8 => 'rampleg1Width',
            9 => 'rampleg1Length',
            10 => 'rampleg1Inclination',
            11 => 'rampleg2Width',
            12 => 'rampleg2Length',
            13 => 'rampleg2Inclination',
            14 => 'rampleg3Width',
            15 => 'rampleg3Length',
            16 => 'rampleg3Inclination',
            17 => 'rampleg4Width',
            18 => 'rampleg4Length',
            19 => 'rampleg4Inclination',
            20 => 'rampBottomEntryareaWidth',
            21 => 'rampBottomEntryareaDepth',
            22 => 'rampTopEntryareaWidth',
            23 => 'rampTopEntryareaDepth',
            24 => 'rampLandingsEntryareaWidth',
            25 => 'rampLandingsEntryareaDepth',
            26 => 'rampSurface',
            27 => 'rampIsHandle',
            28 => 'rampHandleOrientation',
            29 => 'rampHandle1Height',
            30 => 'rampHandle2Height',
            31 => 'skidsLocalization',
            32 => 'skidsInteriorLocalization',
            33 => 'skidsMobility',
            34 => 'skidsInclination',
            35 => 'skidsLength',
            36 => 'rampSkidsHasNotes',
            37 => 'rampSkidsHasDescription',
        ],
        ObjectMetadata::WC => [
            1 => 'wcAccessibility',
            2 => 'wcLocalization',
            3 => 'wcAccessProvidedBy',
            4 => 'wcCabinAccess',
            5 => 'wcCabinLocalization',
            6 => 'wcSwitch',
            7 => 'wcSwitchHeight',
            8 => 'wcCabinWidth',
            9 => 'wcCabinDepth',
            10 => 'wcFlushingBackHeight',
            11 => 'wcFlushingSideHeight',
            12 => 'wcFlushingSideDistanc',
            13 => 'wcFlushing',
            14 => 'wcFlushingDifficulty',
            15 => 'wcHandlesDistance',
            16 => 'wcBasinLeftDistance',
            17 => 'wcBasinRightDistance',
            18 => 'wcBasinBackIndentation',
            19 => 'wcBasinSeatHeight',
            20 => 'wcBasinIsPaperReach',
            21 => 'wcBasinSpace',
            22 => 'wcIsChangingdesk',
            23 => 'wcIsChangingdeskObstructs',
            24 => 'wcChangingdesk',
            25 => 'wcIsAlarmbutton',
            26 => 'wcAlarmbuttonTopHeigh',
            27 => 'wcAlarmbuttonBottomHeight',
            28 => 'wcIsRegularWC',
            29 => 'wcIsRegularWCBrailleMarking',
            30 => 'wcCabinDoorDisposition',
            31 => 'wcCabinWCBasinDisposition',
            32 => 'wcCabinWashBasinDisposition',
            33 => 'wcHasNotes',
            34 => 'wcHasDescription',
            35 => 'hallway1Width',
            36 => 'hallway1Depth',
            37 => 'hallway1DoorWidth',
            38 => 'hallway1DoorMarking',
            39 => 'hallway2Width',
            40 => 'hallway2Depth',
            41 => 'hallway2DoorWidth',
            42 => 'hallway2DoorMarking',
            43 => 'handle1Type',
            44 => 'handle1Height',
            45 => 'handle1Length',
            46 => 'handle2Type',
            47 => 'handle2Height',
            48 => 'handle2Length',
            49 => 'doorWidth',
            50 => 'doorOpeningDirection',
            51 => 'doorIsMarking',
            52 => 'doorHandlePosition',
            53 => 'washbasinHeight',
            54 => 'washbasinUnderpass',
            55 => 'washbasinIsHandle',
            56 => 'washbasinHandleType',
            57 => 'washbasinHandleHeight',
            58 => 'washbasinHandleLength',
            59 => 'tapHeight',
            60 => 'tapType',
        ],
    ];

    /**
     * Vraci prilohy s offsetem
     * @return mixed
     */
    public static function getRelations()
    {
        return self::$relations;
    }

    /**
     * @param string $key
     *
     * @return array
     */
    public static function getColsMap($key = 'main')
    {
        return self::$colsMap[$key];
    }
} 
