INSERT INTO "object_type" ("id", "title", "pair_key", "combine_key") VALUES
  (29,	'WaterParkObjectCategory',	'aquapark',	NULL),
  (30,	'BusStationObjectCategory',	'autobusové nádraží',	NULL),
  (31,	'BankObjectCategory',	'banka',	NULL),
  (32,	'BarObjectCategory',	'bar',	NULL),
  (33,	'BotanicGardenObjectCategory',	'botanická zahrada',	NULL),
  (34,	'PastryObjectCategory',	'cukrárna, kavárna a čajovna',	NULL),
  (35,	'GasStationObjectCategory',	'čerpací stanice',	NULL),
  (36,	'FarmObjectCategory',	'farma a statek',	NULL),
  (37,	'TaxOfficeObjectCategory',	'finanční úřad',	NULL),
  (38,	'StadiumObjectCategory',	'fotbalové hřiště a stadion',	NULL),
  (39,	'GuestHouseObjectCategory',	'penzion',	NULL),
  (40,	'HotelObjectCategory',	'hotel',	NULL),
  (41,	'PubObjectCategory',	'hospoda',	NULL),
  (42,	'FuneralHallObjectCategory',	'smuteční síň',	NULL),
  (43,	'ObservatoryObjectCategory',	'hvězdárna a planetárium',	NULL),
  (44,	'HypermarketObjectCategory',	'hypermarket',	NULL),
  (45,	'InformationCenterObjectCategory',	'informační centrum',	NULL),
  (46,	'CampObjectCategory',	'kemp',	NULL),
  (47,	'CinemaObjectCategory',	'kino',	NULL),
  (48,	'ConcertHallObjectCategory',	'koncertní síň',	NULL),
  (49,	'ContactSocialServiceObjectCategory',	'sociální kontaktní služby',	NULL),
  (50,	'SwimmingObjectCategory',	'koupaliště',	NULL),
  (51,	'IndoorSwimmingPoolObjectCategory',	'krytý plavecký bazén',	NULL),
  (52,	'SpaHouseObjectCategory',	'lázeňský dům',	NULL),
  (53,	'WellnessObjectCategory',	'wellness',	NULL),
  (54,	'PharmacyObjectCategory',	'lékárna',	NULL),
  (55,	'DoctorObjectCategory',	'lékař',	NULL),
  (56,	'MedicalEmergencyObjectCategory',	'lékařská pohotovost',	NULL),
  (57,	'DentalEmergencyObjectCategory',	'zubní pohotovost',	NULL),
  (58,	'AirportObjectCategory',	'letiště',	NULL),
  (59,	'FolkArchitectureObjectCategory',	'lidová architektura',	NULL),
  (60,	'CityHallObjectCategory',	'magistrát',	NULL),
  (61,	'KindergartenObjectCategory',	'mateřská škola',	NULL),
  (62,	'MunicipalityObjectCategory',	'městský úřad',	NULL),
  (63,	'MosqueObjectCategory',	'mešita',	NULL),
  (64,	'HospitalObjectCategory',	'nemocnice',	NULL),
  (65,	'PolyclinicObjectCategory',	'poliklinika',	NULL),
  (66,	'MunicipalOfficeObjectCategory',	'obecní úřad',	NULL),
  (67,	'StoreObjectCategory',	'obchod',	NULL),
  (68,	'DepartmentStoreObjectCategory',	'obchodní dům a nákupní centrum',	NULL),
  (69,	'OpticianShopObjectCategory',	'optika',	NULL),
  (70,	'BreweryObjectCategory',	'pivovar',	NULL),
  (71,	'ResidentialSocialServiceObjectCategory',	'sociální pobytové služby',	NULL),
  (72,	'InsuranceOfficeObjectCategory',	'pojišťovna',	NULL),
  (73,	'PoliceObjectCategory',	'policie ČR',	NULL),
  (74,	'MetropolitanPoliceObjectCategory',	'policie městská',	NULL),
  (75,	'PostOfficeObjectCategory',	'pošta',	NULL),
  (76,	'CarDealerObjectCategory',	'prodejce automobilů',	NULL),
  (77,	'HarborObjectCategory',	'přístav',	NULL),
  (78,	'RecreationalFacilityObjectCategory',	'rekreační zařízení',	NULL),
  (79,	'RestaurantObjectCategory',	'restaurace a pohostinství',	NULL),
  (80,	'FastFoodObjectCategory',	'rychlé občerstvení',	NULL),
  (81,	'ServiceObjectCategory',	'služby',	NULL),
  (82,	'SocialOfficeObjectCategory',	'sociální zabezpečení',	NULL),
  (83,	'CourtObjectCategory',	'soud',	NULL),
  (84,	'SportsFacilityObjectCategory',	'sportovní zařízení',	NULL),
  (85,	'AdministrativeOfficeObjectCategory',	'správní úřad',	NULL),
  (86,	'MetroStationObjectCategory',	'stanice metra',	NULL),
  (87,	'PublicProsecutorObjectCategory',	'státní zastupitelství',	NULL),
  (88,	'HighSchoolObjectCategory',	'střední škola',	NULL),
  (89,	'SupermarketObjectCategory',	'supermarket',	NULL),
  (90,	'WeddingHallObjectCategory',	'svatební síň',	NULL),
  (91,	'SchoolObjectCategory',	'škola',	NULL),
  (92,	'EmploymentOfficeObjectCategory',	'úřad práce',	NULL),
  (93,	'PublicToiletObjectCategory',	'veřejné WC',	NULL),
  (94,	'VeterinarySurgeryObjectCategory',	'veterinární ordinace',	NULL),
  (95,	'ViticultureObjectCategory',	'vinařství',	NULL),
  (96,	'TrainStationObjectCategory',	'vlaková stanice',	NULL),
  (97,	'CollegeObjectCategory',	'vysoká škola a univerzita',	NULL),
  (98,	'BasicSchoolObjectCategory',	'základní škola',	NULL),
  (99,	'EmbassyObjectCategory',	'zastupitelský úřad a ambasáda',	NULL),
  (100,	'HealthInsuranceCompanyObjectCategory',	'zdravotní pojišťovna',	NULL),
  (101,	'MedicalSupplyObjectCategory',	'zdravotnické potřeby',	NULL),
  (102,	'WinterStadiumObjectCategory',	'zimní stadion',	NULL),
  (103,	'ZooObjectCategory',	'zoologická zahrada',	NULL);
